### PR TITLE
fix: don't remove flag value that matches subcommand name

### LINKED ISSUE #1777: flag value misparsed as subcommand
it looks like the parser is having trouble with space delimited persistent flags, where a sub command aligns with the value of the first of many flags:

for `./app -z one -o one two`: https://go.dev/play/p/cKaEuTEhWAZ
wanted:
```
zero: one
one: one
args: []
```
got:
```
zero: -o
one: nil
args: [one two]
```

note: this does not trigger for the following cases
```sh
app -z two two          # only one flag
app -z=two -o=one two   # using equals delimited flags
app -z one -o two two   # colliding value is not first flag
app two -z two -one one # sub command comes first
```

### PR DESCRIPTION
**Pull request by brianpursley**
When the command searches args to find the arg matching a particular subcommand name, it needs to ignore flag values, as it is possible that the value for a flag might match the name of the sub command.

This change improves argsMinusFirstX() to ignore flag values when it searches for the X to exclude from the result.

Fixes #1777

### CODE REVIEW

File: command.go [hunk 1]
```diff
@@ -613,13 +613,37 @@ Loop:
...
-			return ret
+// Special care needs to be taken not to remove a flag value.
+func argsMinusFirstX(args []string, x string, c *Command) []string {
+	if len(args) == 0 {
+		return args
+	}
+	c.mergePersistentFlags()
+	flags := c.Flags()
+
+Loop:
```
Comment (brianpursley) [inline command.go:624]: This logic resembles (but not exactly) that of `stripFlags()` in this same package. I tried to take a similar approach here for consistency.

File: command.go [hunk 2]
```diff
@@ -613,13 +613,37 @@ Loop:
...
+	for pos := 0; pos < len(args); pos++ {
```
Comment (umarcor) [inline command.go:625]: Is there a particular reason to use `for pos := 0; pos < len(args); pos++` instead of `for i, y := range args`?

**Review by jpmcb — COMMENTED** [review]
This overall makes sense but since we'd be chaning the API from
```go
func argsMinusFirstX(args []string, x string)
```
to
```go
argsMinusFirstX(args []string, x string, c *Command)
```
we'd have to wait for Cobra 2.0.0.

File: command.go (hunk 2 above)
Comment (brianpursley) [reply command.go:625]: Sorry, I didn't see you comment until now.

Yes, there is a reason:

Inside the loop, it can advance the position (`pos++` on line 636) in order to handle when there is a flag with an arg and an equal sign is not used (ie `--foo bar`).  In this case it needs to skip over the next token because it is the value of the flag, not an arg.

**Comment by yxxhero** [comment]
any update?

**Comment by brianpursley** [comment]
> any update?

I don't think there are any outstanding questions or changes requested, so it waiting on further review or approval.

**Comment by yxxhero** [comment]
@brianpursley Thanks for your reply. I'm waiting for this PR.

**Review by marckhouzam — CHANGES_REQUESTED** [review]
This look correct to me and I think it is safe with respect to backwards-compatibility.
It will fix the broken case, which I don't see anyone expecting to work as it does now.

Since this PR requires a small rebase, I allowed myself to add two nits that hopefully @brianpursley won't mind addressing at the same time.

Thanks for your patience.

File: command_test.go [hunk 3]
```diff
@@ -2193,3 +2193,92 @@ func TestSetContextPersistentPreRun(t *testing.T) {
...
+	root.PersistentFlags().StringVarP(&bar, "bar", "b", "something", "")
+
+	child := &Command{
+		Use: "child",
+	}
+	root.AddCommand(child)
+
+	testCases := []struct {
+		args          []string
+		expectedFlags []string
```
[the remark this answers is not in the document]
Comment (brianpursley) [reply command_test.go]: Good catch.  I don't know why I called it flags, but you're right, it is not just flags.

I renamed them to `expectedFoundArgs` and `foundArgs`.  Let me know if you have a different name in mind.

**Review by marckhouzam — APPROVED** [review]
Thanks for the quick fix!
LGTM

**Comment by umarcor** [comment]
@marckhouzam please milestone this!

**Comment by marckhouzam** [comment]
> @marckhouzam please milestone this!

This was already milestoned 🙂
