### PR TITLE
Fix flag completion

### LINKED ISSUE #1320: fatal error: concurrent map writes with RegisterFlagCompletionFunc
Cobra has a global map [here](https://github.com/spf13/cobra/blob/master/custom_completions.go#L21) to store completion function when those exists.

This global map is not protected in any way, which leads to `fatal error: concurrent map writes` when handling **multiple root command concurrently**. Yes, it's a little odd situation but it's a useful one to generate documentation/completion faster (ie, concurrently). Most of those documentation/completion generator will actually mutate things here and there in the commands, which makes them not thread-safe. Now, this global map for completion functions also make things no, thread-safe, even if you duplicated entirely your root command.

I see the following possible solutions:
- move this completion function (no map anymore) directly into `flag.Flag`. No more global, no more indirection, but that's another package.
- move the map into `cobra.Command`, to at least make be thread-safe when you have a copy of your `Command`
- add a mutex or use `sync.Map`.

Example code to trigger the issue:

```go
package main

import (
	"fmt"
	"sync"

	"github.com/spf13/cobra"
)

func main() {
	cmd := cobra.Command{}

	N := 2
	options := make([]string, N)

	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		flag := fmt.Sprintf("flag%d", i)
		cmd.Flags().StringVarP(&options[i], flag, "", "value", "usage")
		wg.Add(1)
		go func() {
			defer wg.Done()
			err := cmd.RegisterFlagCompletionFunc(flag, nil)
			if err != nil {
				panic(err)
			}
		}()
	}

	wg.Wait()

}
```

_Originally posted by @krobelus in https://github.com/spf13/cobra/issues/1290#issuecomment-767341378_

### LINKED ISSUE #1437: 1.2.0 regression: flag completion issues
PR #1423 changed the location where flag completion functions are stored. It always stores them under the root cmd. This breaks Podman because we setup each cobra cmd struct individually with their flags before we join them to the root command.
So when we call  `cmd.RegisterFlagCompletionFunc()` the root cmd will not be the actual root cmd. When the `__complete` command tries to look up flag completions it will not find anything in the real root cmd and thus no completion is provided.

ref https://github.com/containers/podman/pull/10841

### PR DESCRIPTION
**Pull request by Luap99**
The flag completion functions should not be stored in the root cmd.
There is no requirement that the root cmd should be the same when
`RegisterFlagCompletionFunc` was called. Storing the flags there does
not work when you add the the flags to your cmd struct before you add the
cmd to the parent/root cmd. The flags can no longer be found in the rigth
place when the completion command is called and thus the flag completion
does not work.

Also #1423 claims that this would be thread safe but we still have a map
which will fail when accessed concurrently. To truly fix this issue use a
RWMutex.

Fixes #1437
Fixes #1320

### CODE REVIEW

**Comment by Luap99** [comment]
@jpmcb @marckhouzam PTAL

Every program who calls cmd.RegisterFlagCompletionFunc() before joining the cmd to the root command will no longer have functional flag completion. I think it will break many applications since it is common to add flags to the cmd before adding it the root/parent cmd.
It would be great if we can get this fixed soon.

**Comment by Luap99** [comment]
OK this patch doesn't work either. Storing them in the correct cmd doesn't work for persistent flags.

I also do not understand what #1423 is supposed to fix. The map is just stored in the root cmd now, writing concurrently will still fail.

**Comment by Luap99** [comment]
OK, this should work now and truly fix the concurrency problem.

File: completions.go [hunk 1]
```diff
@@ -100,15 +107,16 @@ func (c *Command) RegisterFlagCompletionFunc(flagName string, f func(cmd *Comman
...
 
-	root := c.Root()
-	if _, exists := root.flagCompletionFunctions[flag]; exists {
+	if _, exists := flagCompletionFunctions[flag]; exists {
 		return fmt.Errorf("RegisterFlagCompletionFunc: flag '%s' already registered", flagName)
 	}
-	if root.flagCompletionFunctions == nil {
-		root.flagCompletionFunctions = map[*pflag.Flag]func(cmd *Command, args []string, toComplete string) ([]string, ShellCompDirective){}
+	if flagCompletionFunctions == nil {
+		flagCompletionFunctions = map[*pflag.Flag]func(cmd *Command, args []string, toComplete string) ([]string, ShellCompDirective){}
```
Comment (marckhouzam) [inline completions.go:117]: You no longer need this nil-check, since the map is already initialized at the start.

File: completions_test.go [hunk 2]
```diff
@@ -1763,13 +1763,15 @@ func TestFlagCompletionWithNotInterspersedArgs(t *testing.T) {
...
 	}
-	rootCmd.AddCommand(childCmd, childCmd2)
 	childCmd.Flags().Bool("bool", false, "test bool flag")
 	childCmd.Flags().String("string", "", "test string flag")
 	_ = childCmd.RegisterFlagCompletionFunc("string", func(cmd *Command, args []string, toComplete string) ([]string, ShellCompDirective) {
 		return []string{"myval"}, ShellCompDirectiveDefault
 	})
 
+	// Important: only add the commands after RegisterFlagCompletionFunc was called
+	rootCmd.AddCommand(childCmd, childCmd2)
```
Comment (marckhouzam) [inline completions_test.go:1773]: I realize we are trying to fix this quickly, so sorry for the nit, but I feel this should be a separate test, and it should mention in a comment issue #1437 to explain why the order is important

File: completions_test.go [hunk 3]
```diff
@@ -1969,6 +1971,21 @@ func TestFlagCompletionWithNotInterspersedArgs(t *testing.T) {
 	if output != expected {
 		t.Errorf("expected: %q, got: %q", expected, output)
 	}
+
+	// Test that no flag completion works on a subcmd
```
Comment (marckhouzam) [inline completions_test.go:1975]: Is this comment right? It seems the "no" is superfluous.

**Review by marckhouzam — COMMENTED** [review]
Thanks for the quick reaction @Luap99 !

This look good with a couple of nits.  

However, I haven't tested if it really fixes the concern of istioctl mentioned in https://github.com/spf13/cobra/pull/1423#issue-676809165, but I expect it would.

**Comment by marckhouzam** [comment]
@silenceshell are you able to test if this fix addresses the concern you were aiming to fix for istioctl in https://github.com/spf13/cobra/pull/1423#issue-676809165?

**Comment by silenceshell** [comment]
> @silenceshell are you able to test if this fix addresses the concern you were aiming to fix for istioctl in [#1423 (comment)](https://github.com/spf13/cobra/pull/1423#issue-676809165)?

This PR could fix the istioctl test cases, RWMutex is safe enough.

**Comment by Luap99** [comment]
@marckhouzam Updated.

**Comment by silenceshell** [comment]
> OK this patch doesn't work either. Storing them in the correct cmd doesn't work for persistent flags.
> 
> I also do not understand what #1423 is supposed to fix. The map is just stored in the root cmd now, writing concurrently will still fail.

Sorry for the incomplete consideration. 
Istio has some tests that call rootCmd reg func concurrently, #1423 wants to store the map to rootCmd to avoid concurrent map writes errors. This could fix that problem but breaks the current implement. sorry for this again, and thanks for the correction.

**Review by marckhouzam — APPROVED** [review]
This looks good.
I was able to reproduce the regression with Helm, and can confirm this PR fixes things.
I had not seen the regression because most of helm flags that use completion are on the root command.

Thanks @Luap99 

@jpmcb what do you think for a 1.2.1 release?

**Review by jpmcb — APPROVED** [review]
Merging to get a quick fix out for this regression. Thanks all for the fast find and quick testing efforts on this!

**Comment by Luap99** [comment]
@jpmcb Thanks for the quick review and the new release tag.
