### PR TITLE
cmd: Fix license issues

### LINKED ISSUE #311: GPL Text LGPL Header
The LICENCE text for the GPL licences is correct, but the installed licence headers are LGPL. Can these two be separated into GPL and LGPL.

### LINKED ISSUE #318: Missing relevant GNU licenses LGPL and AGPL
These relevant GNU licenses seem to be missing:
1. GNU Lesser General Public License (LGPL); and
2. GNU Affero General Public License (AGPL).

File `cobra/cmd/licenses.go` apparently comprises the supported licenses.

Source: GNU's [How to choose a license for your own work](https://www.gnu.org/licenses/license-recommendations.html).

### LINKED ISSUE #322: GPL 3 license header extra whitespace
The GPL 3 license header [ends with extra whitespace](mdb/refactor-licenses-to-many-files).

(A tab, followed by a newline, comprises the last line.)

### PR DESCRIPTION
**Pull request by bogem**
Fixes #311
Fixes #318 
Fixes #322
Closes #356

/cc @MarkDBlackwell @eparis @spf13

### CODE REVIEW

File: cobra/cmd/license_gpl_3.go [hunk 1]
```diff
@@ -18,23 +18,22 @@ package cmd
 func initGpl3() {
 	Licenses["gpl3"] = License{
 		Name:            "GNU General Public License 3.0",
-		PossibleMatches: []string{"gpl3", "gpl", "gnu gpl3", "gnu gpl"},
+		PossibleMatches: []string{"gpl3", "gplv3", "gpl", "gnu gpl3", "gnu gpl"},
```
Comment (pombredanne) [inline cobra/cmd/license_gpl_3.go]: FWIW, a bare gpl or gnu gpl would be a "GPL 1.0 or later, but never a GPL 3.0. The GPL's are clear on the topic: no version means any version hence GPL 1.0 or later

File: cobra/cmd/license_gpl_3.go [hunk 2]
```diff
@@ -18,23 +18,22 @@ package cmd
...
 		Header: `
 This file is part of {{ .appName }}.
 
 {{ .appName }} is free software: you can redistribute it and/or modify
-it under the terms of the GNU Lesser General Public License as published by
+it under the terms of the GNU General Public License as published by
```
Comment (pombredanne) [inline cobra/cmd/license_gpl_3.go]: Part of my PR in https://github.com/spf13/cobra/pull/356 was to avoid having parametrized appname in the notice which is a bummer for license detection. https://github.com/spf13/cobra/pull/356/files#diff-71e2b7d85e97ba305901d44ea0223e76R441 
I see you did not carry this around: any reason?

File: cobra/cmd/license_lgpl.go [hunk 3]
```diff
@@ -0,0 +1,188 @@
+package cmd
+
+func initLgpl() {
+	Licenses["lgpl"] = License{
+		Name:            "GNU Lesser General Public License",
+		PossibleMatches: []string{"lgpl", "lesser gpl", "gnu lgpl"},
```
Comment (pombredanne) [inline cobra/cmd/license_lgpl.go]: A plain LGPL resolves to LGPL 2.0 or later not an LGPL 3.0
And a plain lesser gpl resolves to LGPL 2.1 or later not an LGPL 3.0

File: cobra/cmd/license_gpl_3.go (hunk 2 above)
Comment (bogem) [inline cobra/cmd/license_gpl_3.go]: I noticed what you avoid it, but I read specification on [official gpl site](https://www.gnu.org/licenses/gpl-howto.en.html) what the header contains an app name:
```
    This file is part of Foobar.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
```

File: cobra/cmd/license_lgpl.go (hunk 3 above)
Comment (bogem) [inline cobra/cmd/license_lgpl.go]: Thank you for your remark! I don't know much about licenses.
So I will use LGPL 2.1 as it good for LGPL such as for lesser GPL. Or it's not right?

File: cobra/cmd/license_gpl_3.go (hunk 1 above)
Comment (bogem) [inline cobra/cmd/license_gpl_3.go]: Ok, thank you for this remark.
I will use "gpl" match for GPL 2.0

File: cobra/cmd/license_lgpl.go (hunk 3 above)
Comment (bogem) [inline cobra/cmd/license_lgpl.go]: And could please send a link to official info, where it says?

Comment (bogem) [inline cobra/cmd/license_lgpl.go]: And for plain LGPL in GNU you can see LGPL 3.0: https://www.gnu.org/licenses/lgpl.txt

File: cobra/cmd/license_gpl_3.go (hunk 1 above)
Comment (pombredanne) [inline cobra/cmd/license_gpl_3.go]: your call :) FWIW  https://www.gnu.org/licenses/gpl-3.0.html#section14 ` If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation.`
This applies to all the version of the GPL1,2 and 3 BTW.

File: cobra/cmd/license_gpl_3.go (hunk 2 above)
Comment (pombredanne) [inline cobra/cmd/license_gpl_3.go]: This is not a spec. This is a suggestion. And a  terrible suggestion that creates a bazillion variants of the GPL notices... I can detect them alright in [ScanCode](https://github.com/nexB/scancode-toolkit)  anyway but it is best to avoid this variants IMHO.

File: cobra/cmd/license_lgpl.go (hunk 3 above)
Comment (pombredanne) [inline cobra/cmd/license_lgpl.go]: As you can see in the archive.org the text of the license has changed over time at the same URL: https://web-beta.archive.org/web/*/https://www.gnu.org/licenses/lgpl.txt    and the LGPL states in section 6: https://www.gnu.org/licenses/lgpl-3.0.html#section6
`If the Library as you received it does not specify a version number of the GNU Lesser General Public License, you may choose any version of the GNU Lesser General Public License ever published by the Free Software Foundation.` and this applies to the LGPL 2.0, 2.1 and 3.0. So a plain LGPL can be any version 2 or later and a  Less GPL can be any version 2.1 or later.

Comment (pombredanne) [inline cobra/cmd/license_lgpl.go]: Sorry to bug you with all this BTW.... but I am maintainer a license scanner tool... so I know a tad too many things about licenses. And may be I care too much about accuracy there ;)

File: cobra/cmd/license_gpl_3.go (hunk 2 above)
Comment (bogem) [inline cobra/cmd/license_gpl_3.go]: Okay, I will avoid the app name. It also makes program easier

File: cobra/cmd/license_gpl_3.go (hunk 1 above)
Comment (bogem) [inline cobra/cmd/license_gpl_3.go]: So I can leave plain gpl as gplv3?

File: cobra/cmd/license_lgpl.go (hunk 3 above)
Comment (bogem) [inline cobra/cmd/license_lgpl.go]: So I can leave plain lpgl as lgplv3?
