### PR TITLE
Fix multiple fish completion issues

### LINKED ISSUE #1214: Fish completion fails with quotes in argument
The fish completion script prints ugly traces if quotes are not balanced in the argument.

To reproduce: `./testprog '[TAB]`

```fish
> ./testprog '- (line 1): Unexpected end of string, quotes are not balanced
./testprog __complete ' 
                      ^
in command substitution
        called on line 35 of file -
in function '__testprog_perform_completion' with arguments './testprog\ \''
        called on line 1 of file -
in command substitution
        called on line 71 of file -
in function '__testprog_prepare_completions'
in command substitution
```

This happens with single and double quotes. Technically the completion still works and offers file completion but the traces makes this unusable.

I also checked this with zsh, bash, #1146 and #1208 but only fish is affected. All other shells offer file completion, which is in my eyes the right thing.

### LINKED ISSUE #1248: Fish completion does not handle "nospace" or file completion properly
This is the same bug that is present for `zsh` and described in #1211 and #1212.

**Bug 1: File completion is not respected**

The `fish` completion script performs file completion only if it receives no completions:
https://github.com/spf13/cobra/blob/b97b5ead31f7d34f764ac8666e40c214bb8e06dc/fish_completions.go#L151

However, it is valid for `ValidArgsFunction` to return completions that don't apply to the current `toComplete` prefix.  This means file completion should be performed, but the script does not realize it as it still believes it received valid completions.

Say I have the following `ValidArgsFunction` for command `withfile`:
```
ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
    // We do not consider the toComplete prefix and always return a completion
    return []string{"why"}, cobra.ShellCompDirectiveDefault
},
``` 
If I have a file called `myfile` and run in `fish`:
```
$ ./testprog withfile my<TAB>
```
I would expect to get file completion and get `myfile` as a completion, but I don't.  This is because
```
$ ./testprog __complete withfile my<ENTER>
why
:0
Completion ended with directive: ShellCompDirectiveDefault
```
Notice that above, the script would receive a completion even though it is not technically valid.  This is allowed.  But then, the script does not realize it must do file completion.

**Bug 2: NoSpace is not respected all the time**

For the exact same reason, `ShellCompDirectiveNoSpace` also fails when the `__complete` command returns completions that don't match the `toComplete` prefix.

Say I have the following `ValidArgsFunction` for command `nospace`:
```
ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) == 0 {
			return []string{"when\tThe time", "who\tThe person"}, cobra.ShellCompDirectiveNoSpace
		}
		return []string{"why\tThe reason"}, cobra.ShellCompDirectiveNoSpace
	},
``` 

If I run in `fish`:
```
$ ./testprog nospace whe<TAB>
```
a space is added after `./testprog nospace when ` even though the `ShellCompDirectiveNoSpace` was given.

This is because the script only handles `ShellCompDirectiveNoSpace` if a single completion is returned:
https://github.com/spf13/cobra/blob/b97b5ead31f7d34f764ac8666e40c214bb8e06dc/fish_completions.go#L144

But my `ValidArgsFunction` does not filter the completions but instead returns all of them, leaving `fish` to filter them.  In this case:
```
$ ./testprog __complete nospace whe<ENTER>
when	The time
who	The person
:2
Completion ended with directive: ShellCompDirectiveNoSpace
```
Notice that with the result above the completion script would receive two completions even though the `who` completion is not technically valid. This is allowed.

**Bug 3: NoSpace not respected with descriptions**

Finally, the nospace logic for fish does not handle the case when there is a description.  To achieve "nospace" the script adds a second completion with an extra "." to prevent the shell from adding a space. However if there is a description, the extra "." is added to the description instead of the completion, and the nospace directive does not work. 

I will post a PR to handle this better.

### LINKED ISSUE #1303: Fish completion fails when command line starts with a space
If the current command line starts with a space the completion fails. It will only provide file completion.

Note: This is valid syntax used to prevent the shell from writing the command to the history.

BASH_COMP_DEBUG_FILE output:
```
commandLine is:  podman 
Starting __podman_perform_completion with:  podman 
args:  podman 
last arg: 
Setting emptyArg
emptyArg: ""
Cannot find . No completions.
Completion results: 
No completion, probably due to a failure
```

I think this line causes the problem:
https://github.com/spf13/cobra/blob/7df62f7668c7fbeafd6dbb45ad0294f4ea08c0ec/fish_completions.go#L33
We need to trim $argv before we can split on space

This bug was originally reported by @pastalian in https://github.com/containers/podman/issues/8829

### LINKED ISSUE #1306: Fish completion does not work with env vars in the program path
Using an environment variable or a `~` when using a path for the program breaks shell completion for fish.
For instance:
```
$HOME/testprog [TAB]
~/testprog [TAB]
```
currently don't work for fish. This is because of the use of `type -q` in the script.

### PR DESCRIPTION
**Pull request by marckhouzam**
Fixes #1248
Fixes #1303
Fixes #1214
Fixes #1306

This PR fixes multiple bugs in the fish completion script.

Please ses each issue for details.

### CODE REVIEW

**Comment by marckhouzam** [comment]
Here is how to test this specific fix.  An extensive test program is included at the bottom.

**Test 1 - ShellCompDirectiveNoSpace not respected**
Before the PR:
```
$ fish
$ ./testprog completion fish | source

$ ./testprog nospace compo<TAB>
# and
$ ./testprog --nospace compo<TAB>
```
will complete to:
```
$ ./testprog nospace compost<SPACE>
# and
$ ./testprog --nospace compost<SPACE>
```
the `<SPACE>` is wrong at the end of the completion because `ValidArgsFunction` requested `ShellCompDirectiveNoSpace`, as can be seen by:
```
$ ./testprog __complete nospace compo
complete	description1
compost	description2
:2
Completion ended with directive: ShellCompDirectiveNoSpace
```
Testing with this PR in the exact same way will not output the `<SPACE>` after the word `compost`.

**Test 2 - ShellCompDirectiveNoSpace not properly handling descriptions**

The nospace logic for fish does not handle the case when there is a description. To achieve "nospace" the script adds a second completion with an extra "." to prevent the shell from adding a space. However if there is a description, the extra "." is added to the description instead of the completion, and the nospace directive does not work.

Before the PR:
```
$ fish
$ ./testprog completion fish | source

$ ./testprog nospace first compo<TAB>
```
will complete to:
```
$ ./testprog nospace first compo<SPACE>
```
the `<SPACE>` is wrong at the end of the completion because `ValidArgsFunction` requested `ShellCompDirectiveNoSpace`, as can be seen by:
```
$ ./testprog __complete nospace compo
compost	description2
:2
Completion ended with directive: ShellCompDirectiveNoSpace
```
**Notice** this is slightly different than the previous case because a single completion is returned by the `__complete` command, but the `<SPACE>` is still added, this time because of the description.

Testing with this PR in the exact same way will not output the `<SPACE>` after the word `compost`.

**Test 3 - File completion not always done when requested**

Before the PR:
```
$ fish
$ ./testprog completion fish | source
$ touch myfile

$ ./testprog withfile myfi<TAB>
```
will **not** perform file completion and will **not** show `myfile` although it should have.

Testing with this PR in the exact same way will trigger file completion and will show `myfile` as expected.

**Extensive test program to execute the above tests, but also any regression tests:**
```
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var completionNoDesc bool

var completionCmd = &cobra.Command{
	Use:   "completion [bashzsh|fish|powershell]",
	Short: "Generate completion script",
	Long: `To load completions:

Bash:

$ source <(testprog completion bash)

# To load completions for each session, execute once:
Linux:
  $ testprog completion bash > /etc/bash_completion.d/testprog
MacOS:
  $ testprog completion bash > /usr/local/etc/bash_completion.d/testprog

Zsh:

$ source <(testprog completion zsh)
$ compdef _testprog testprog

# To load completions for each session, execute once:
$ testprog completion zsh > "${fpath[1]}/_testprog"

Fish:

$ testprog completion fish | source

# To load completions for each session, execute once:
$ testprog completion fish > ~/.config/fish/completions/testprog.fish

PowerShell:

PS C:\> testprog completion powershell | Out-String | Invoke-Expression

To load completions for every new session, add the output of the above command
to your powershell profile.
`,
	DisableFlagsInUseLine: true,
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"bash\tBash completion", "zsh", "fish", "powershell"}, cobra.ShellCompDirectiveNoFileComp
	},
	Args: cobra.ExactValidArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		switch args[0] {
		case "bash":
			cmd.Root().GenBashCompletion(os.Stdout)
		case "zsh":
			if !completionNoDesc {
				cmd.Root().GenZshCompletion(os.Stdout)
			} else {
				cmd.Root().GenZshCompletionNoDesc(os.Stdout)
			}
		case "fish":
			cmd.Root().GenFishCompletion(os.Stdout, !completionNoDesc)
		case "powershell":
			cmd.Root().GenPowerShellCompletion(os.Stdout)
		}
	},
}

var rootCmd = &cobra.Command{
	Use: "testprog",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("rootCmd called")
	},
}

var vargsCmd = &cobra.Command{
	Use:        "vargs",
	Short:      "Cmd with ValidArgs AND a subcmd",
	ValidArgs:  []string{"one", "two", "three"},
	ArgAliases: []string{"un", "deux", "trois"},
	Args:       cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("vargsCmd called")
	},
}

var childVargsCmd = &cobra.Command{
	Use:   "childVargs",
	Short: "Child command",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("childVargs called")
	},
}

var aliasCmd = &cobra.Command{
	Use:     "cmdWithAlias",
	Short:   "Command with aliases",
	Aliases: []string{"aliasCmd", "cmdAlias"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("cmdWithAlias called")
	},
}

// A command with no short description
var nodescriptionCmd = &cobra.Command{
	Use: "nodesc",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("nodesc called")
	},
}

// File filtering for the first argument
// Replaces MarkZshCompPositionalArgumentFile(1, string{"*.log", "*.txt"})
var filterFileCmd = &cobra.Command{
	Use:   "filterFile",
	Short: "Only list file of type [*.log,*.txt]",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) == 0 {
			return []string{"log", "txt"}, cobra.ShellCompDirectiveFilterFileExt
		}
		// No more expected arguments, so turn off file completion
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("filterFile called")
	},
}

// Turn off file completion for all arguments
var noFileCmd = &cobra.Command{
	Use:   "nofile",
	Short: "No file completion done",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("nofile called")
	},
}

// Full file completion for arguments
var fullFileCmd = &cobra.Command{
	Use:   "fullFile [filename]",
	Short: "Full file completion",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("fullFile called")
	},
}

// Only allow directory name completion and only for the first argument
var dirOnlyCmd = &cobra.Command{
	Use:   "dirOnly [dirname]",
	Short: "Only list directories in completion",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) == 0 {
			return nil, cobra.ShellCompDirectiveFilterDirs
		}
		// No more expected arguments, so turn off file completion
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("dirOnly called")
	},
}

// Only allow directory name from within a specified directory and only for the first argument
var subdirCmd = &cobra.Command{
	Use:   "subdir [sub-dirname]",
	Short: "Only list directories within themes/",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) == 0 {
			return []string{"themes"}, cobra.ShellCompDirectiveFilterDirs | cobra.ShellCompDirectiveNoFileComp
		}
		// No more expected arguments, so turn off file completion
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("subdir called")
	},
}

// Test file completion when returning other completions
var compAndFileCmd = &cobra.Command{
	Use:   "compAndFile [sun|moon|<filename>]",
	Short: "Provide some completions and file completion when prefix does not match",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) != 0 {
			return []string{"nginx", "thanos"}, cobra.ShellCompDirectiveNoFileComp
		}
		var completions []string
		for _, comp := range []string{"install", "uninstall"} {
			completions = append(completions, comp)
		}
		return completions, cobra.ShellCompDirectiveDefault
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("compAndFile called")
	},
}

var colonCmd = &cobra.Command{
	Use:       "cmdColonArgs",
	Short:     "Command with colon args",
	ValidArgs: []string{"first:ONE", "first:SECOND"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("colonCmd called")
	},
}

var longDescCmd = &cobra.Command{
	Use:       "cmdLongDesc12345678901234567890123456789012345678901234567890",
	Short:     `We have here a quite long description which should go over the length of the shell width.  What should we do with such a long description? zsh and fish handle it nicely, so we should prepare bash to handle it in the same fashion`,
	ValidArgs: []string{"first:ONE", "first:SECOND"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("colonCmd called")
	},
}

var specialCharDescCmd = &cobra.Command{
	Use:   "specialChar",
	Short: "Description contains chars like ` and maybe others",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("specialChar cmd called")
	},
}

var noSpaceCmd = &cobra.Command{
	Use:   "nospace",
	Short: "followed by completion with noSpace, even for file completion",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		comps := []string{"complete\tdescription1", "compost\tdescription2"}
		if len(args) == 0 {
			// Allow file completion with ShellCompDirectiveNoSpace
			return comps, cobra.ShellCompDirectiveNoSpace
		}

		var finalComps []string
		for _, comp := range comps {
			if strings.HasPrefix(comp, toComplete) {
				finalComps = append(finalComps, comp)
			}
		}
		return finalComps, cobra.ShellCompDirectiveNoSpace
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("nospace cmd called")
	},
}

var sentenceCmd = &cobra.Command{
	Use:   "sentence",
	Short: "completion has spaces",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		// Allow file completion with ShellCompDirectiveNoSpace
		return []string{"comp is a sentence\tFirst comp", "and another sentence\tsecondComp"}, cobra.ShellCompDirectiveNoFileComp
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("sentence cmd called")
	},
}

var withfileCmd = &cobra.Command{
	Use:   "withfile",
	Short: "completion always returned and has file completion",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		// We do not consider the toComplete prefix and always return a completion
		return []string{"why"}, cobra.ShellCompDirectiveDefault
	},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("withfile cmd called")
	},
}

func setFlags() {
	rootCmd.Flags().String("theme", "", "theme to use (located in /themes/THEMENAME/)")
	rootCmd.Flags().SetAnnotation("theme", cobra.BashCompSubdirsInDir, []string{"themes"})

	rootCmd.Flags().String("theme2", "", "theme to use (located in /themes/THEMENAME/)")
	rootCmd.RegisterFlagCompletionFunc("theme2", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"themes"}, cobra.ShellCompDirectiveFilterDirs
	})

	rootCmd.Flags().String("customComp", "", "test custom comp for flags")
	rootCmd.RegisterFlagCompletionFunc("customComp", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"firstComp\tthe first value", "secondComp\tthe second value", "forthComp\tthe forth value"}, cobra.ShellCompDirectiveNoFileComp
	})

	rootCmd.Flags().StringP("file", "f", "", "list files")
	rootCmd.Flags().String("longdesc", "", "before newline\nafter newline")

	rootCmd.Flags().BoolP("bool", "b", false, "bool flag")
	rootCmd.Flags().BoolSliceP("bslice", "B", nil, "bool slice flag")

	rootCmd.PersistentFlags().StringP("persistent", "p", "", "persistent flag")

	// rootCmd.Flags().String("required", "", "required flag")
	// rootCmd.MarkFlagRequired("required")

	vargsCmd.Flags().StringP("nonpersistent", "n", "", "non persistent local flag")

	// If there is only a recommended value before we reach the equal sign or the colon, then the completion works as expected.
	// If the values differ afterwards, completion fails in bash, but works in fish and zsh
	rootCmd.Flags().String("equalSignWorks", "", "test custom comp with equal sign")
	rootCmd.RegisterFlagCompletionFunc("equalSignWorks", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"first=Comp\tthe first value", "second=Comp\tthe second value", "forth=Comp\tthe forth value"}, cobra.ShellCompDirectiveNoFileComp
	})

	rootCmd.Flags().String("equalSignWorksNot", "", "test custom comp with equal sign")
	rootCmd.RegisterFlagCompletionFunc("equalSignWorksNot", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"first=Comp1\tthe first value", "first=Comp2\tthe second value", "first=Comp3\tthe forth value"}, cobra.ShellCompDirectiveNoFileComp
	})

	rootCmd.Flags().String("colonWorks", "", "test custom comp with colon one value works")
	rootCmd.RegisterFlagCompletionFunc("colonWorks", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"first:ONE\tthe first value", "second\tthe second value", "forth\tthe forth value"}, cobra.ShellCompDirectiveNoFileComp
	})

	rootCmd.Flags().String("colonWorksNot", "", "test custom comp with colon doesnt work")
	rootCmd.RegisterFlagCompletionFunc("colonWorksNot", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"first:ONE\tthe first value", "first:SECOND\tthe second value", "second:Comp1\tthe forth value"}, cobra.ShellCompDirectiveNoFileComp
	})

	rootCmd.Flags().String("nospace", "", "test custom comp with nospace directive")
	rootCmd.RegisterFlagCompletionFunc("nospace", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"complete\tFirst comp", "compost\tsecondComp"}, cobra.ShellCompDirectiveNoSpace
	})

	rootCmd.Flags().StringArray("array", []string{"allo", "toi"}, "string array flag")
}

func main() {
	completionCmd.Flags().BoolVar(
		&completionNoDesc,
		"no-descriptions", false,
		"disable completion description for shells that support it")
	rootCmd.AddCommand(completionCmd)

	rootCmd.AddCommand(
		filterFileCmd,
		noFileCmd,
		fullFileCmd,
		dirOnlyCmd,
		subdirCmd,
		compAndFileCmd,
		nodescriptionCmd,
		vargsCmd,
		colonCmd,
		aliasCmd,
		longDescCmd,
		specialCharDescCmd,
		noSpaceCmd,
		sentenceCmd,
		withfileCmd,
	)

	vargsCmd.AddCommand(childVargsCmd)
	setFlags()
	rootCmd.Execute()
}

```

**Comment by marckhouzam** [comment]
Waiting for review

File: fish_completions.go [hunk 1]
```diff
@@ -28,9 +28,9 @@ function __%[1]s_debug
 end
 
 function __%[1]s_perform_completion
-    __%[1]s_debug "Starting __%[1]s_perform_completion with: $argv"
+    __%[1]s_debug "Starting __%[1]s_perform_completion"
 
-    set args (string split -- " " "$argv")
+    set args (string split -- " " (commandline -c))
```
Comment (Luap99) [inline fish_completions.go:33]: Given that you are already touching this line can you change it to
```suggestion
    set args (string split -- " " (string trim (commandline -c)))
```
Please check #1303 for details. I already checked that both `$argv` or `commandline -c` have to be trimmed

Comment (marckhouzam) [reply fish_completions.go:33]: Thanks @Luap99 !
I will update with your findings.

Comment (Luap99) [reply fish_completions.go:33]: Actually it has to be:
```suggestion
    set args (string split -- " " (string trim -l (commandline -c)))
```
Only trim the left spaces as the right ones are required if complete an empty arg (e.g. ` command [TAB]`).

Comment (marckhouzam) [reply fish_completions.go]: Done.
Thanks again!

**Comment by marckhouzam** [comment]
This PR now addresses 5 different fish completion issues.

We have Go tests for the completion logic in Cobra that is coded in Go.  Those tests can be found in `custom_completions_test.go`.  However, we don't have tests to exercise the actual completion script coded in shell script.  This makes it more difficult to make changes to those shell scripts without worrying about causing some regression.

To try to address this concern, I have setup a regression-testing project for the Cobra completion scripts.
It is currently able to test the `fish` and the `bash` scripts.  Specifically for `fish`, it has tests that fail for each issue this PR is fixing and that pass with this PR applied.  This gives me good confidence in this PR.

If anyone is interested it should be simple to run those tests locally:
https://github.com/marckhouzam/cobra-completion-testing

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
@marckhouzam CI is red. You have to rebase.

File: fish_completions.go [hunk 2]
```diff
@@ -30,7 +30,7 @@ end
 function __%[1]s_perform_completion
     __%[1]s_debug "Starting __%[1]s_perform_completion"
 
-    set args (string split -- " " (commandline -c))
+    set args (string split -- " " (string trim -l (commandline -c)))
```
Comment (krobelus) [inline fish_completions.go:33]: Should be `string trim -- -l (commandline -c)`

---

Often it's not necessary to pass the current token to fish.
Rather, one can just compute all possible tokens because fish will filter them anyway.
Sometimes it can be useful to do the filtering in the app (for example if it's not feasible to enumerate all possible tokens), so it's fine.

File: fish_completions.go [hunk 3]
```diff
@@ -43,16 +43,13 @@ function __%[1]s_perform_completion
     end
     __%[1]s_debug "emptyArg: $emptyArg"
 
-    if not type -q "$args[1]"
-        # This can happen when "complete --do-complete %[2]s" is called when running this script.
```
Comment (krobelus) [inline fish_completions.go:47]: Removing this seems sensible. I'm not sure if the comment really matters, because the this fish completion script should only be sourced when the command exists.

File: fish_completions.go [hunk 4]
```diff
@@ -43,16 +43,13 @@ function __%[1]s_perform_completion
...
-    end
-
     set requestComp "$args[1] %[3]s $args[2..-1] $emptyArg"
     __%[1]s_debug "Calling $requestComp"
 
-    set results (eval $requestComp 2> /dev/null)
+    # Call the command as a sub-shell so that we can redirect any errors
+    # For example, if $requestComp has an unmatched quote
+    # https://github.com/spf13/cobra/issues/1214
+    set results (fish -c "$requestComp" 2> /dev/null)
```
Comment (krobelus) [inline fish_completions.go:52]: Hmm this is interesting. If you didn't include the token at the cursor this wouldn't be a problem.

Usually completions want to use `commandline -opc`, which gives all words left of the cursor, which always tokenize successfully.

It also restricts the tokens to  the current process (`-p`). Observe bind running
```
bind \eg 'commandline -c'
```
and then type `echo foo; echo bar` and <kbd>Ctrl>/kbd>+<kbd>g</kbd>.
So `-p` is usually correct for completions.

The `-o` flag is useful because it already does word splitting, then there is no need for `string split " "`.

File: fish_completions.go (hunk 1 above)
Comment (krobelus) [reply fish_completions.go]: This line should probably be `set args (commandline -opc)`.
If the token at the cursor is really required, `(commandline -ct)` can be appended.

File: fish_completions.go (hunk 4 above)
Comment (krobelus) [reply fish_completions.go:52]: OK I've played around with this some more, and found a version that should tick all boxes, while not needing a separate fish process. Here's what I would do:

```fish
function __%[1]s_perform_completion
    set -l args (commandline -opc)
    set -l lastArg (commandline -ct)
    set -l requestComp $args[1] %[3]s $args[2..-1] (string escape -- $lastArg)
    if test -d $args[1]
        return 1
    end
    set -l results (eval $requestComp 2> /dev/null)
```

- `set -l` is a minor detail: if a user defines a universal variable with `set -U x foo`, then `set x` inside this function would overwrite the user's variable. This is an ugly edge case in fish which should probably be changed, but for now we can force variables to be local by use `set -l` when they are used for the first time in a function.
- `(commandline -ct)` gives us the raw token at the cursor, including any unclosed quotes. To avoid https://github.com/spf13/cobra/issues/1214, we can simply escape it. This means that variables in the token at the cursor will not be evaluated, but that's a general issue with user-defined fish completions, and I don't think it's an important problem.
- If the command is a directory I got  some errors (trying to complete `./testprog `), so I added a check for that.

File: fish_completions.go [hunk 5]
```diff
@@ -137,49 +126,65 @@ function __%[1]s_prepare_completions
...
+        # Important not to quote the variable for count to work
+        set numComps (count $__%[1]s_comp_results)
+        __%[1]s_debug "numComps: $numComps"
+
+        if test $numComps -eq 1; and test $nospace -ne 0
+            # To support the "nospace" directive we trick the shell
+            # by outputting an extra, longer completion.
+            # We must first split on \t to get rid of the descriptions because
+            # the extra character we add to the fake second completion must be
+            # before the description.  We don't need descriptions anyway since
```
Comment (krobelus) [inline fish_completions.go:153]: This is clever, and works reliably as far as I can tell.
However, the upcoming fish 3.2.0 will always show the pager on ambiguous completions (https://github.com/fish-shell/fish-shell/issues/6924). This would cause some confusion.

So I'm not sure if this an overall improvement. Who are the users of this option?
Fish already gets this right a lot of times by hardcoding the character set `@=/:.,` - if a completion ends in one of these characters, then no space will be inserted.

File: fish_completions.go [hunk 6]
```diff
@@ -137,49 +126,65 @@ function __%[1]s_prepare_completions
...
+    if test $nospace -ne 0; or test $nofiles -eq 0
+        set prefix (commandline -t)
+        __%[1]s_debug "prefix: $prefix"
+
+        set completions
+        for comp in $__%[1]s_comp_results
+            if test (string match -e -r -- "^$prefix" "$comp")
+                set -a completions $comp
+            end
+        end
```
Comment (krobelus) [inline fish_completions.go:140]: In case this is relevant: the regex should be escaped, just in case, and this loop can be done in one line because `string match` accepts multiple arguments. I'd also eschew the `-e` option, I think that option was a mistake.

```fish
set prefix (commandline -t | string escape --style=regex)
...
set -l completions (string match -r -- "^$prefix.*" $__%[1]s_comp_results)
```

File: fish_completions.go (hunk 3 above)
Comment (marckhouzam) [reply fish_completions.go:47]: This scenario is pretty obscure actually.  Let me explain.  

Fish comes with existing completion scripts.  For instance, it has its own `helm` completion script:
https://github.com/fish-shell/fish-shell/blob/master/share/completions/helm.fish
This is script is out of date however and provides some completions that are no longer valid for `helm`.

In the Cobra script this PR updates, we do `complete -c helm -e` to erase all other completions for `helm`.  The problem is that the old `helm` script included in fish may not yet be loaded, which means the user could get completions from both scripts (the old one provided by fish, and the Cobra one).  To fix this, the Cobra script does `complete --do-complete "helm " > /dev/null 2>&1` which forces the loading of the old completion script, so that all these completions can be erased by `complete -c helm -e`.

**The problem happens for programs that are not on PATH**.  In this case, if the Cobra completion script is sourced more than once, calling for example, `complete --do-complete "myprog " > /dev/null 2>&1` would cause fish to print an error because it cannot find `myprog`, and this error printout could not be redirected to `/dev/null`.  To fix that I was catching this special case with `if not type -q "$args[1]"` above.

However, with @Luap99's help, we have found a way to redirect such error to `/dev/null` (see line 52 below).  That is why we no longer need to catch this special case and can remove this code.

File: fish_completions.go (hunk 6 above)
Comment (marckhouzam) [reply fish_completions.go:140]: Thanks for the improvements @krobelus !

> the regex should be escaped, just in case,

Sounds safer, I'll add this.

> and this loop can be done in one line because `string match` accepts multiple arguments.

Nice!  I admit I was upset at having to do the loop.  Now it can be removed!

> I'd also eschew the `-e` option, I think that option was a mistake.

Actually, according to the following doc, I understood that using `-e` was preferred to adding the suffix `.*`, so I went that route: https://fishshell.com/docs/current/cmds/string-match.html

File: fish_completions.go (hunk 5 above)
Comment (marckhouzam) [reply fish_completions.go:153]: > This is clever, and works reliably as far as I can tell.
> However, the upcoming fish 3.2.0 will always show the pager on ambiguous completions ([fish-shell/fish-shell#6924](https://github.com/fish-shell/fish-shell/issues/6924)). This would cause some confusion.

Ouch, that will indeed cause confusion for the "nospace" case.

> So I'm not sure if this an overall improvement. Who are the users of this option?

For example, Helm uses this option when completing a chart's full name which is comprised of `<repository>/<chartname>`; the completion first provides all repository names in the form `<repository>/`, and once the slash is present on the command-line, the completion will add the possible chart names, but there should be no space between the two.  This is much more efficient for helm than having to provide all the full `<repository>/<chartname>` from the very start.

`kubectl cp <pod>:<file>` could also use this option to avoid adding a space after the `:`.

> Fish already gets this right a lot of times by hardcoding the character set `@=/:.,` - if a completion ends in one of these characters, then no space will be inserted.

Cool!  I was not aware of this.  This would address both cases I mentioned.  I tested it and it works as you describe.
But I don't know if there are other cases that wouldn't end with `@=/:.,`.  At a minimum, we could turn off this hack for if the completion ended with `@=/:.,`.  I'll have to think what to do for the other (possible) cases for fish 3.2.  Let me know if you have any suggestions.

File: fish_completions.go (hunk 4 above)
Comment (marckhouzam) [reply fish_completions.go:52]: Thanks!  I'll take the time to look into this as soon as I can and get back to you.

File: fish_completions.go (hunk 2 above)
Comment (marckhouzam) [reply fish_completions.go:33]: > Should be `string trim -- -l (commandline -cp)`

I don't understand from the documentation what the `-p` flag does.  Could you clarify?

> Often it's not necessary to pass the current token to fish.
> Rather, one can just compute all possible tokens because fish will filter them anyway.
> Sometimes it can be useful to do the filtering in the app (for example if it's not feasible to enumerate all possible tokens), so it's fine. (the `testprog` examples show that the current token is necessary to complete `--flags`)

Right.  So originally, I thought the program should do the filtering, but with experience, I now realize it is actually better to provide `fish` (and `zsh`) with all unfiltered completions so that the shell can do smarter matching than simply on prefix.  For example, if the user types `prog paw<TAB>`, giving shell completions like `bearpaw` will allow it to still match even though it is not on the prefix.

As you saw in this PR however, I didn't find a way to find out if `fish` had found a smart match or not, so, when wanting to do file completion, I was forced to filter on prefix in the script itself, to know if there would be a match or not.  This is because Cobra only wants to do file completion if there are no valid completions, so it can be consistent with `bash` and `zsh`.  This was not ideal, so if you know of a way to figure out in the script if fish will match on a list of completion, that would be helpful.

**Comment by marckhouzam** [comment]
> @marckhouzam CI is red. You have to rebase.

Thanks for the heads up @Luap99 . I rebased on master to get the 2021 date fix which were the cause of the failure.

File: fish_completions.go (hunk 5 above)
Comment (krobelus) [reply fish_completions.go:153]: One could sidestep the completion engine and directly insert the unique completion if nospace is set

```fish
$ function sneaky-complete
      commandline --replace -t nospace
  end
$ complete -e sneaky-complete; complete -c sneaky-complete -a '(sneaky-complete)' -f
```

According to my tests this works (although it rings the terminal bell, because fish thinks there are no completions). However, I'd advise against it. You are not meant to modifiy the commandline *during* the computation of a completion. That can break other completions, though I didn't find an example here.

fish has not added an option to control the add-a-space behavior yet because AFAIK no real use case has been brought up that doesn't work with the hardcoded list.

I fear that the cost of adding a hack to support this outweighs the benefits.
I think we should drop this until we see a real need. Then an option can be added to fish, avoiding the need for a hacky workaround.

File: fish_completions.go (hunk 6 above)
Comment (krobelus) [reply fish_completions.go:140]: The `-e` thing is just an opinion, anything works of course. My point is, without it the regex is easier to understand by someone who doesn't know this flag.

File: fish_completions.go (hunk 2 above)
Comment (krobelus) [reply fish_completions.go:33]: The `-p` is explained in https://github.com/spf13/cobra/pull/1249#discussion_r563333005. Sorry for the wall of text :smile_cat: 

fish does fuzzy substring matching if there is no prefix or exact match. This is currently not exposed in a scriptable way.

I wonder if it's acceptable to do file completions only if there are no results. Doesn't sound too good, so probably the prefix comparison is better (maybe make that substring matching instead of only prefix).

File: fish_completions.go (hunk 3 above)
Comment (krobelus) [reply fish_completions.go:47]: > This is script is out of date however and provides some completions that are no longer valid for helm.

So the fish script should be changed to a single line `helm completion fish | source`?
Ok this is https://github.com/fish-shell/fish-shell/issues/7357, no one has done that yet. I'll try to do that, I just need to detect the Helm version.

> In the Cobra script this PR updates, we do complete -c helm -e to erase all other completions for helm.

In an ideal world this would not be necessary, because fish's version is installed to, say `/usr/share/fish/completions/helm.fish` but the one that ships with the Helm package is in `/usr/share/fish/vendor_completions.d/helm.fish`, which overrides the former because it's earlier in `$fish_complete_path`.

But for manual (and repeated) sourcing we do need this, so you are right.

I feel like the best solution is to check at the call site if the program is executable:

```fish
if type -q "%[2]s"
    complete --do-complete "%[2]s " > /dev/null 2>&1
end
```

Starting a new fish instance to be able to redirect the error seems a bit overkill.
fish always sources its startup files, so the new instance might cause obscure issues; better to use `eval` (as suggested below).

File: fish_completions.go (hunk 5 above)
Comment (Luap99) [reply fish_completions.go:153]: I took a look how I use the `ShellCompDirectiveNoSpace` option in podman. Almost all cases ends with one of `=:,` but not all. I found one case where I set this when it ends with a `-`. https://github.com/containers/podman/blob/479fc226044b745ecaafc2d5fa925afe6ca06de0/cmd/podman/common/completion.go#L603-L608
Even more importantly there is a case where I set this together with `ShellCompDirectiveDefault` (path completion). This case does not work with fish currently. It works for bash and zsh.

Comment (krobelus) [reply fish_completions.go:153]: Thanks for investigating. I guess we should just [add `-`](https://i.redd.it/vtttn02gchsz.jpg) to the set of separators in fish.

Regarding the nospace+path, is this what you mean:

```go
// cobra-completion-testing/testprog/testprog.go
var noSpaceCmdPrefix = &cobra.Command{
	Use:   "nospace",
	Short: "Directive: no space",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return nil, cobra.ShellCompDirectiveNoSpace
	},
	Run: func(cmd *cobra.Command, args []string) {},
}
```

```
testprog/bin/testprog prefix nospace <TAB>
```

this gives me files in both fish and bash (I've merged this branch and the bash v2 one).
If I return some completions instead of `nil`, then I only get those completions in both shells (as expected).

You probably mean something else?

Comment (Luap99) [reply fish_completions.go:153]: Bash does not add a space after the completed path. Fish does.

Comment (Luap99) [reply fish_completions.go:153]: Honestly I don't think adding `-` make much sense. This might solve my specific problem but doesn't solve the problem here.
`cobra` allows me as developer to set `nospace` wherever I want, not only on those characters. I don't see a reason why fish should limit my options as a completion script developer.

File: fish_completions.go (hunk 2 above)
Comment (marckhouzam) [reply fish_completions.go:33]: > I wonder if it's acceptable to do file completions only if there are no results. 

You mean if the program returns no completions?  This is what the script does right now (before this PR). But that requires that the program do the filtering on itself.  This PR is (in part) trying to improve that situation. By doing the filtering in the fish script, it will allow the program to return all completions, which will then allow the fuzzy matching you mention.  The fuzzy matching will only not work when file completion is requested or when nospace is requested, both of which are the less common cases.

> Doesn't sound too good, so probably the prefix comparison is better (maybe make that substring matching instead of only prefix).

As long as we use an algorithm that is stricter than what fish does, we could indeed improve compared to filtering on prefix.  Do you know where I could see the algorithm used by fish?  Or else I'll just play around and try to see if any pattern match seems to work.

File: fish_completions.go (hunk 3 above)
Comment (marckhouzam) [reply fish_completions.go:47]: > So the fish script should be changed to a single line `helm completion fish | source`?
> Ok this is [fish-shell/fish-shell#7357](https://github.com/fish-shell/fish-shell/issues/7357), no one has done that yet. I'll try to do that, I just need to detect the Helm version.

You can probably prefix the existing script with something like
```
if helm completion -h | grep -q fish > /dev/null
    helm completion fish | source
else
   # Existing old script
end
```
Note that `helm completion fish` will return a success code even if the command does not exist (#1156), that is why I suggest using the help text to figure out if fish is supported.

> In an ideal world this would not be necessary, because fish's version is installed to, say `/usr/share/fish/completions/helm.fish` but the one that ships with the Helm package is in `/usr/share/fish/vendor_completions.d/helm.fish`, which overrides the former because it's earlier in `$fish_complete_path`.

You are right.  We could choose not to support the explicit sourcing.  In fact, Cobra does not support it for `zsh`.  However, I do find it nicer to support it, as long as the side-effects can be easily controlled.
 
> But for manual (and repeated) sourcing we do need this, so you are right.

👍 

> I feel like the best solution is to check at the call site if the program is executable:
> 
> ```fish
> if type -q "%[2]s"
>     complete --do-complete "%[2]s " > /dev/null 2>&1
> end
> ```

I think that would work, and it is better.  However we thought about adding the extra fish instance to solve another issue where an error was being thrown when a quote was not properly closed, see #1214 

> Starting a new fish instance to be able to redirect the error seems a bit overkill.
> fish always sources its startup files, so the new instance might cause obscure issues; better to use `eval` (as suggested below).

We currently use eval, but it prints error message we cannot catch in the case of #1214

Comment (krobelus) [reply fish_completions.go:47]: > However, I do find explicit sourcing nicer

Yeah, I think it's fine.

> We currently use eval, but it prints error message we cannot catch

The error can be cleanly avoided by escaping `lastArg`, see https://github.com/spf13/cobra/pull/1249#discussion_r563348012.

File: fish_completions.go (hunk 2 above)
Comment (krobelus) [reply fish_completions.go:33]: Just to clarify for myself; the common cases are
- no files
- only files because the program returns no completions

in those cases fish already does all the filtering. But if we're in between - the program returns some completions but they may not match the token - we want to filter in the completion script. That sounds great.

I agree that this is probably not very common. Most programs should take either custom tokens (like subcommands) or files, not both. Git is a notable exception, but Git completion computes custom file paths based on `git ls-files`.

I'd just ignore nospace for fish for now until, it behaves the right way most of the time already.
I can't think of a good solution right now, it needs support from fish.

> Do you know where I could see the algorithm used by fish?

The two most permissive filters are [here](https://github.com/fish-shell/fish-shell/blob/062f24d91b199780ae7a8493988549a5f651423f/src/wcstringutil.cpp#L206-L214). I think they can be implemented like this:

```fish
$ function fishy_match -a needle haystack
      if string match -irq -- (string escape --style=regex -- $needle) $haystack
          echo substr match
      end
      if string match -rq -- (string split -- '' $needle | string escape --style=regex | string join '.*?') $haystack
          echo subseq match
      end
  end
$ fishy_match String 'case-insensitive substring match'
substr match
$ fishy_match foo follow
subseq match
```

I use `-r` and regex escaping because the needle might contain globs, which would be interpreted by `string match` without `-r`.

File: fish_completions.go (hunk 4 above)
Comment (marckhouzam) [reply fish_completions.go:52]: @krobelus I finally had a chance to try your suggestion above.  I really love the fact that we no longer have to explicitly check for an empty lastArg thanks to the escaping.  Thanks for all your help!

I will put `-l` everywhere there is a `set` of a new variable.

I've also slightly modified your suggestion to do the escaping right away when calculating `lastArg`; if find it easier to read.

File: fish_completions.go (hunk 3 above)
Comment (marckhouzam) [reply fish_completions.go:47]: > The error can be cleanly avoided by escaping lastArg, see #1249 (comment).

That works!
So we can do as you suggest:
```
if type -q "%[2]s"
    complete --do-complete "%[2]s " > /dev/null 2>&1
end
```
and avoid having to call a new fish shell to avoid error printouts.

@Luap99 you may be interested in trying the version I will soon push.  But I can confirm that I tested it for unmatched quotes, and completion simply isn't done, with no error message.   Also, the regression tests repo passes as before.

File: fish_completions.go (hunk 2 above)
Comment (marckhouzam) [reply fish_completions.go]: > Most programs should take either custom tokens (like subcommands) or files, not both. 

There are some cases where both are valid.  Helm for example can accept the reference to a remote chart, or the local path to a chart.  What I've done in helm is have the program return the list of files as completions to do both file completion and custom token completion.

I think it is important to keep all shells behaving the same for Cobra because the program returns a list of completions to be used by all shells; we don't want to make the program have to behave differently for each shell.

But we could, as a separate effort, support doing file completion even if there are custom token completion matches.  This was not Cobra's previous behaviour, so I had never considered it myself, but I believe it could be done for all shells.  Maybe a future effort...

> I'd just ignore nospace for fish for now until, it behaves the right way most of the time already.
> I can't think of a good solution right now, it needs support from fish.

Well, our current solution is good until fish 3.2.  And then, when fish shows the choices including the fake one with a trailing `.`,  it may be confusing, but I think it may be not much worse than letting the shell add and unwanted space.

PENDING - I'll turn off adding the extra `.` when fish handles the case itself following the characters you mentioned.

PENDING - And I'll also adapt the filtering based on the algos you've provided.

I feel that after all that, we'll have something really solid for fish completion.

File: fish_completions.go (hunk 5 above)
Comment (marckhouzam) [reply fish_completions.go]: > Even more importantly there is a case where I set this together with ShellCompDirectiveDefault (path completion). 
> Bash does not add a space after the completed path. Fish does.

@Luap99 I never planned for this case.  And now that you mention it, I realize it also does not work for `zsh`.  It is an easy fix though.  I will add it to #1213.  And I see that you made it work for powershell 🎉 .  I don't believe there is anything we can do for `fish` though.  

Out of curiosity, what kind of situation would not want a space after file completion?

Comment (marckhouzam) [reply fish_completions.go]: Turns out preventing a space after file completion for `zsh` also prevents the trailing `/` from being added after a directory.  At least in the way I've found to prevent a space.  I think a missing `/` is a bigger problem than the extra space, so I'll leave it alone.

Comment (marckhouzam) [reply fish_completions.go]: To get back to the 'nospace' directive for fish, the latest version of this PR keeps the "hack" that adds an extra fake completion but only when the completion does not end with `@=/:.,`.  I think this is the best we can do at this time.

File: fish_completions.go (hunk 2 above)
Comment (krobelus) [reply fish_completions.go]: > What I've done in helm is have the program return the list of files as completions to do both file completion and custom token completion.

Ideally we could tell the shell that we also want file completons, because it can see through variables to tokens like `$PWD/`. Something for the future I guess. The implementation would be a bit hacky:
essentially, you'd need two calls to `complete -c`, one with `-f` and one without.
Each of them has a condition (the `-n` part). If the condition for the one with file completions is true, then fish will also provide file completions (in addition to the provided custom completions).

> we don't want to make the program have to behave differently for each shell.

In terms of what completions to offer, definitely. Of course shells differ in how they display completions.
By default, fish sorts completions, but you can add the `--keep-order` flag to the `complete -c` call, then the program is in control of the ordering.

> I feel that after all that, we'll have something really solid for fish completion.

Yeah, latest changes look great! For some programs  it's hard to compete with manually written completions, but it should work great for conventional programs.

File: fish_completions.go (hunk 5 above)
Comment (Luap99) [reply fish_completions.go]: > Out of curiosity, what kind of situation would not want a space after file completion?

Simple answer `podman/docker run --volume`. This flag accepts a volume name or a path followed by a colon and again a path. This is my current autocompletion function:
```
func AutocompleteVolumeFlag(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	volumes, _ := getVolumes(cmd, toComplete)
	directive := cobra.ShellCompDirectiveNoSpace | cobra.ShellCompDirectiveDefault
	if strings.Contains(toComplete, ":") {
		// add space after second path
		directive = cobra.ShellCompDirectiveDefault
	}
	return volumes, directive
}
```
After the first path I do not want the space added. The user has to type a colon here. After the colon you get only path completion and then I a space should be added.

> Turns out preventing a space after file completion for zsh also prevents the trailing / from being added after a directory. At least in the way I've found to prevent a space. I think a missing / is a bigger problem than the extra space, so I'll leave it alone.

I am totally fine if it does not work. It is just a small corner case.

**Review by jpmcb — APPROVED** [review]
I've tested this with the test program Mark provided and also with his cobra-completion-testing repo. I'm confident this is good to go since all those are passing and work as I'd expect!! Thanks for the hard work and patience on this one! :fish:

**Comment by jpmcb** [comment]
@marckhouzam We'll need to fix the merge conflicts as I've been merging PRs this morning

**Comment by marckhouzam** [comment]
@jpmcb The rebase is done.  The tests in https://github.com/marckhouzam/cobra-completion-testing all pass now except one which is related to the poor handling of `--` by the completion code.  I don't quite recall which conversation made me add this test (surely an exchange with @Luap99), but I am confident it is unrelated to this PR.

Thanks so much for getting so many PRs merged today!  This is very exciting!

**Comment by Luap99** [comment]
@marckhouzam I guess the `--` test is for https://github.com/spf13/cobra/pull/1308
