### PR TITLE
fix RegisterFlagCompletionFunc concurrent map writes error

### LINKED ISSUE #1320: fatal error: concurrent map writes with RegisterFlagCompletionFunc
Cobra has a global map [here](https://github.com/spf13/cobra/blob/master/custom_completions.go#L21) to store completion function when those exists.

This global map is not protected in any way, which leads to `fatal error: concurrent map writes` when handling **multiple root command concurrently**. Yes, it's a little odd situation but it's a useful one to generate documentation/completion faster (ie, concurrently). Most of those documentation/completion generator will actually mutate things here and there in the commands, which makes them not thread-safe. Now, this global map for completion functions also make things no, thread-safe, even if you duplicated entirely your root command.

I see the following possible solutions:
- move this completion function (no map anymore) directly into `flag.Flag`. No more global, no more indirection, but that's another package.
- move the map into `cobra.Command`, to at least make be thread-safe when you have a copy of your `Command`
- add a mutex or use `sync.Map`.

Example code to trigger the issue:

```go
package main

import (
	"fmt"
	"sync"

	"github.com/spf13/cobra"
)

func main() {
	cmd := cobra.Command{}

	N := 2
	options := make([]string, N)

	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		flag := fmt.Sprintf("flag%d", i)
		cmd.Flags().StringVarP(&options[i], flag, "", "value", "usage")
		wg.Add(1)
		go func() {
			defer wg.Done()
			err := cmd.RegisterFlagCompletionFunc(flag, nil)
			if err != nil {
				panic(err)
			}
		}()
	}

	wg.Wait()

}
```

_Originally posted by @krobelus in https://github.com/spf13/cobra/issues/1290#issuecomment-767341378_

### PR DESCRIPTION
**Pull request by silenceshell**
Some CI system(like istio) will call package of istioctl in parallel, if cobra use `flagCompletionFunctions` as a global var, will generate `fatal error: concurrent map writes`.
So it is better to store those functions to `flagCompletionFunctions` as a map of root command(thread-safe), instead of a global var.

ref #1320 (this PR will not fix it, as we only get thread-safe, but no lock for multi threads)

### CODE REVIEW

**Comment by silenceshell** [comment]
@jpmcb would you like to review this PR? Thanks a lot!

File: command.go [hunk 1]
```diff
@@ -88,6 +88,9 @@ type Command struct {
 	// group commands.
 	Annotations map[string]string
 
+	//flagCompletionFunctions is map of flag completion functions.
+	flagCompletionFunctions map[*flag.Flag]func(cmd *Command, args []string, toComplete string) ([]string, ShellCompDirective)
```
Comment (marckhouzam) [inline command.go:92]: Could you move this a little lower to be with other non-public fields?

Comment (silenceshell) [reply command.go]: Thanks for your response! 
Nice advice, I have moved `flagCompletionFunctions` after `globNormFunc`.

**Review by marckhouzam — APPROVED** [review]
Thanks @silenceshell, I think this is simple and safe improvement regarding the global map.

/cc @jpmcb

**Comment by silenceshell** [comment]
@marckhouzam Thanks for your review.
Will this PR be merged to the next release? #1388
I am working on adding completion support for `istioctl`, and look forward for the next release to support flag completion for `istioctl`, this will make the command more handy.

**Comment by marckhouzam** [comment]
> @marckhouzam Thanks for your review.
> Will this PR be merged to the next release? 

I hope so, but it's up to the maintainers.

> I am working on adding completion support for `istioctl`, ...

Cool!  I've just started using `istioctl` and noticed it was lacking full completion.  Thanks for your work on that.

**Review by jpmcb — APPROVED** [review]
This is great! And thanks for bringing this back to the community. LGTM!
